Kyligence/spark

core/src/main/scala/org/apache/spark/storage/BlockInfoManager.scala
=> fix blockInfomanager

yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala, yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala, yarn/src/main/scala/org/apache/spark/deploy/yarn/security/AMCredentialRenewer.scala, yarn/src/main/scala/org/apache/spark/deploy/yarn/security/CredentialUpdater.scala
=> fix kerberos

core/src/main/scala/org/apache/spark/ContextCleaner.scala
related https://github.com/kyligence/kap/issues/13396
=> #33 fix the thread leaks in ContextCleaner

core/src/test/scala/org/apache/spark/ui/UISeleniumSuite.scala
=> ignore unstable ut

core/src/main/scala/org/apache/spark/ContextCleaner.scala, core/src/main/scala/org/apache/spark/ExecutorAllocationManager.scala, core/src/main/scala/org/apache/spark/MapOutputTracker.scala, core/src/main/scala/org/apache/spark/storage/BlockManagerMaster.scala, core/src/main/scala/org/apache/spark/storage/BlockManagerMasterEndpoint.scala, core/src/main/scala/org/apache/spark/storage/BlockManagerMessages.scala, core/src/main/scala/org/apache/spark/storage/BlockManagerSlaveEndpoint.scala, core/src/main/scala/org/apache/spark/util/Utils.scala, core/src/test/scala/org/apache/spark/ExecutorAllocationManagerSuite.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/SQLExecution.scala
related KAP issue: Kyligence/KAP#15009
=> #57 Remove the reliance of dynamic resource allocation on External shuffle service

sql/core/src/main/scala/org/apache/spark/sql/execution/limit.scala
=> #73 [follow up] support limit offset

sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/basicLogicalOperators.scala, sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/SparkStrategies.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/limit.scala
=> #73 support limit offset

pom.xml
=> update Parquet dependency.

pom.xml
=> minor, add local nexus

pom.xml
This reverts commit 3f330c4f9ab310b1fbc046f316f2730af15a0658.
=> Revert "minor, add local nexus"

assembly/pom.xml, common/network-common/pom.xml, common/network-shuffle/pom.xml, common/sketch/pom.xml, common/tags/pom.xml, common/unsafe/pom.xml, core/pom.xml, core/src/main/scala/org/apache/spark/internal/config/ConfigReader.scala, examples/pom.xml, external/flume-assembly/pom.xml, external/flume-sink/pom.xml, external/flume/pom.xml, external/kafka-0-10-assembly/pom.xml, external/kafka-0-10-sql/pom.xml, external/kafka-0-10/pom.xml, external/kafka-0-8-assembly/pom.xml, external/kafka-0-8/pom.xml, graphx/pom.xml, launcher/pom.xml, mllib-local/pom.xml, mllib/pom.xml, repl/pom.xml, sql/catalyst/pom.xml, sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala, sql/core/pom.xml, sql/hive/pom.xml, streaming/pom.xml, tools/pom.xml
=> #11 SQLConf support thread local prop

sql/core/src/main/scala/org/apache/spark/sql/execution/SparkStrategies.scala
=> KE-11849 supoort limit offset pushdown

sql/core/src/main/java/org/apache/spark/sql/execution/datasources/parquet/SpecificParquetRecordReaderBase.java, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala
=> #118 s3 file read retry

sql/core/src/main/scala/org/apache/spark/sql/execution/ui/SQLAppStatusListener.scala
=> #120 shuffle records read

core/src/main/scala/org/apache/spark/deploy/JsonProtocol.scala, core/src/test/scala/org/apache/spark/deploy/DeployTestUtils.scala, core/src/test/scala/org/apache/spark/deploy/JsonProtocolSuite.scala
=> KC-2391, expose app's coreperslave to master json

core/src/main/scala/org/apache/spark/SparkEnv.scala, core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala, core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala, core/src/main/scala/org/apache/spark/deploy/security/HadoopFSDelegationTokenProvider.scala, core/src/main/scala/org/apache/spark/util/Utils.scala
=> Kyspark 3.0.0.x 4.x 3

core/src/main/scala/org/apache/spark/broadcast/BroadcastManager.scala, core/src/main/scala/org/apache/spark/scheduler/DAGScheduler.scala, core/src/main/scala/org/apache/spark/scheduler/TaskSetManager.scala
=> performance issue when gc blocks

pom.xml
=> KC-6297, add profile adl-support

sql/core/src/main/java/org/apache/spark/sql/execution/datasources/parquet/SpecificParquetRecordReaderBase.java, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala, sql/core/src/main/scala/org/apache/spark/sql/util/S3FileUtils.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveStrategies.scala
=> KE-19992 s3 read retry before accessing FileStatus properties

core/src/main/scala/org/apache/spark/log4j/LocalFileAppender.java, core/src/main/scala/org/apache/spark/log4j/SensitivePatternLayout.java, dev/deps/spark-deps-hadoop-2.7-hive-2.3, dev/deps/spark-deps-hadoop-3.2-hive-2.3, pom.xml
=> KE-19958: support SparkExecutorHdfsLogAppender

core/src/main/scala/org/apache/spark/deploy/JsonProtocol.scala, core/src/test/scala/org/apache/spark/deploy/DeployTestUtils.scala, core/src/test/scala/org/apache/spark/deploy/JsonProtocolSuite.scala
=> KE-19998, add more metrics to applicationinfo

core/src/main/scala/org/apache/spark/rdd/CartesianRDD.scala
KE-20353 # avoid cartesian partition oom
=> KE-20353 # avoid cartesian partition oom

core/src/main/scala/org/apache/spark/deploy/history/EventLogFileWriters.scala, core/src/main/scala/org/apache/spark/scheduler/EventLoggingListener.scala, core/src/main/scala/org/apache/spark/scheduler/SparkListener.scala, core/src/test/scala/org/apache/spark/deploy/history/EventLogTestHelper.scala
=> KE-19989 spark eventlog roll up

sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/catalog/SessionCatalog.scala
=> KC-6885 use fine-grained lock in SessionCatalog.tableExists

pom.xml
=> Revert "KE-25484"

pom.xml
=> upgrade parquet version

sql/hive/src/main/scala/org/apache/spark/sql/hive/TableReader.scala
=> KC-7417: support skip csv header in hive partition table

assembly/pom.xml
=> update kafka client version

resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/Config.scala, resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/LoggingPodStatusWatcher.scala
=> KY-895, add config KUBERNETES_DELETE_DRIVER

sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/FSNamespaceUtils.scala
=> KE-34191 fix replace partition table storage path

pom.xml
=> AL-5357 fix api-util in profile hadoop2.7 and update to r52

dev/make-distribution.sh, pom.xml
=> KE-34276 exclude spark examples

core/src/main/scala/org/apache/spark/deploy/history/EventLogFileCompactor.scala, core/src/main/scala/org/apache/spark/deploy/history/EventLogFileWriters.scala, core/src/test/scala/org/apache/spark/deploy/history/EventLogFileCompactorSuite.scala, core/src/test/scala/org/apache/spark/deploy/history/EventLogFileReadersSuite.scala, core/src/test/scala/org/apache/spark/deploy/history/EventLogFileWritersSuite.scala, core/src/test/scala/org/apache/spark/deploy/history/FsHistoryProviderSuite.scala
=> KE-31356 fix event log ut 

core/src/test/scala/org/apache/spark/ExternalShuffleServiceSuite.scala, core/src/test/scala/org/apache/spark/ShuffleNettySuite.scala, core/src/test/scala/org/apache/spark/ShuffleOldFetchProtocolSuite.scala, core/src/test/scala/org/apache/spark/ShuffleSuite.scala, core/src/test/scala/org/apache/spark/SortShuffleSuite.scala
=> KE-31356 minor change shuffleSuite

sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/Attribution.scala, sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/aggregate/WindowFunnel.scala
=> attribution - update event ordering & contrib calculation

sql/core/src/main/scala/org/apache/spark/sql/internal/BaseSessionStateBuilder.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSessionStateBuilder.scala
=> KC-11004 compatible for spark 3.1

sql/core/src/main/scala/org/apache/spark/sql/catalyst/util/V2ExpressionBuilder.scala
=> KE-37052 translate boolean column to V2Predicate

core/src/main/scala/org/apache/spark/storage/BlockManagerMasterEndpoint.scala
=> KE-37170 fix broadcastManager NPE

sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/Extract.java, sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/GeneralScalarExpression.java, sql/catalyst/src/main/java/org/apache/spark/sql/connector/util/V2ExpressionSQLBuilder.java, sql/core/src/main/scala/org/apache/spark/sql/catalyst/util/V2ExpressionBuilder.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/H2Dialect.scala, sql/core/src/test/scala/org/apache/spark/sql/jdbc/JDBCV2Suite.scala
=> [SPARK-38899][SQL]DS V2 supports push down datetime functions

pom.xml
AL-6446 upgrade jackson and jackson-databind version
=> AL-6446 upgrade jackson and jackson-databind version

external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/v2/DB2IntegrationSuite.scala, external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/v2/OracleIntegrationSuite.scala, external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/v2/PostgresIntegrationSuite.scala, external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/v2/V2JDBCTest.scala, sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/GeneralScalarExpression.java, sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/UserDefinedScalarFunc.java, sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/aggregate/UserDefinedAggregateFunc.java, sql/catalyst/src/main/java/org/apache/spark/sql/connector/util/V2ExpressionSQLBuilder.java, sql/catalyst/src/main/scala/org/apache/spark/sql/internal/connector/ToStringSQLBuilder.scala, sql/core/src/main/scala/org/apache/spark/sql/catalyst/util/V2ExpressionBuilder.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSourceStrategy.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/V2ScanRelationPushDown.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/DB2Dialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/DerbyDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/H2Dialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/JdbcDialects.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/MsSqlServerDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/MySQLDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/OracleDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/PostgresDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/TeradataDialect.scala, sql/core/src/test/scala/org/apache/spark/sql/connector/DataSourceV2FunctionSuite.scala, sql/core/src/test/scala/org/apache/spark/sql/jdbc/JDBCV2Suite.scala
=> [SPARK-39148][SQL] DS V2 aggregate push down can work with OFFSET or LIMIT

core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala
=> KE-36175 update private token

resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile
=> minor fix dockerfile java version and host user

core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala
=> KE-36175 [FOLLOWUP] fix hadoop 2.7.4 not compatible

pom.xml
=> add hadoop version hadoop-2.10

resource-managers/yarn/pom.xml, sql/core/pom.xml
=> minor fix hadoop-2.10 package

sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala, sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/stringExpressions.scala, sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/StringExpressionsSuite.scala
add replace function
KE-38347: need support this function
No
add UT
=> KE-38347 add replace function

core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala
=> KE-36175 [FOLLOWUP] fix read-write separation mode

pom.xml, sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala, sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/stringExpressions.scala, sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/StringExpressionsSuite.scala
=> Kyspark 2.2.1.x 3.x zhaohang

resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/Config.scala, resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/KubernetesClientApplication.scala, resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/LoggingPodStatusWatcher.scala
=> KY-895 Spark driver pod cleanup when application is completed

core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala
=> merge ke-4.5.17-sp1 to trunk

core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala, external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/v2/DB2IntegrationSuite.scala, external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/v2/OracleIntegrationSuite.scala, external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/v2/PostgresIntegrationSuite.scala, external/docker-integration-tests/src/test/scala/org/apache/spark/sql/jdbc/v2/V2JDBCTest.scala, pom.xml, sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/GeneralScalarExpression.java, sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/UserDefinedScalarFunc.java, sql/catalyst/src/main/java/org/apache/spark/sql/connector/expressions/aggregate/UserDefinedAggregateFunc.java, sql/catalyst/src/main/java/org/apache/spark/sql/connector/util/V2ExpressionSQLBuilder.java, sql/catalyst/src/main/scala/org/apache/spark/sql/internal/connector/ToStringSQLBuilder.scala, sql/core/src/main/scala/org/apache/spark/sql/catalyst/util/V2ExpressionBuilder.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSourceStrategy.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/V2ScanRelationPushDown.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/DB2Dialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/DerbyDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/H2Dialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/JdbcDialects.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/MsSqlServerDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/MySQLDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/OracleDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/PostgresDialect.scala, sql/core/src/main/scala/org/apache/spark/sql/jdbc/TeradataDialect.scala, sql/core/src/test/scala/org/apache/spark/sql/connector/DataSourceV2FunctionSuite.scala, sql/core/src/test/scala/org/apache/spark/sql/jdbc/JDBCV2Suite.scala
=> cherry pick commit from kyspark 3.2 

core/src/main/scala/org/apache/spark/security/ShellBasedGroupsMappingProvider.scala
…vider
This PR proposes to avoid using `bash -c` in `ShellBasedGroupsMappingProvider`. This could allow users a command injection.
For a security purpose.
Virtually no.
Manually tested.
Closes #36315 from HyukjinKwon/SPARK-38992.
Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
=> KE-38192  Avoid using bash -c in ShellBasedGroupsMappingProvider

sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala, sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/stringExpressions.scala, sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/StringExpressionsSuite.scala
Cherry pick  from kyspark-2.2.1.x-3.x-zhaohang
What changes were proposed in this pull request?
add replace function
Why are the changes needed?
KE-38347: need support this function
Does this PR introduce any user-facing change?
No
How was this patch tested?
add UT
=> Cherry pick KE-38347 add replace function (#519)  from kyspark-2.2.1.x-3.x-zhaohang

resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/VolcanoFeatureStep.scala, resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/k8s/features/VolcanoFeatureStepSuite.scala
=> KE-38771: config volcano config using spark conf

pom.xml
=> KE-39406 Due to a security breach, upgrade commons-text from 1.9 to 1.10.0

pom.xml
=> kyspark-3.2.x-4.x-qa cherrypick into kyspark-3.2.x-4.x 

resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/k8s/KubernetesClusterSchedulerBackend.scala
=> KE-39980 configMap Binds the KE pod

pom.xml
=> KE-40102 fix snyk vulnerabilities, upgrade ivy from 2.5.0 ro 2.5.1

pom.xml
=> KE-40007 Fix vulnerability, upgrade jackson-databind

pom.xml
=> KE-40047 fix snyk vulnerabilities, upgrade ivy from 2.5.0 to 2.5.1

pom.xml
=> KE-40102 fix snyk vulnerabilities, upgrade ivy from 2.5.0 to 2.5.1

pom.xml
=> AL-7433 Fix vulnerabilities

pom.xml
=> AL-7626 Fix vulnerabilities

core/src/main/scala/org/apache/spark/internal/config/package.scala, core/src/main/scala/org/apache/spark/rdd/AsyncRDDActions.scala, core/src/main/scala/org/apache/spark/rdd/RDD.scala, core/src/main/scala/org/apache/spark/rpc/netty/MessageLoop.scala, core/src/test/scala/org/apache/spark/FileSuite.scala, core/src/test/scala/org/apache/spark/executor/CoarseGrainedExecutorBackendSuite.scala, core/src/test/scala/org/apache/spark/rdd/RDDSuite.scala, pom.xml, resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/k8s/KubernetesClusterSchedulerBackend.scala, sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/SparkPlan.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/InMemoryFileIndex.scala, sql/core/src/test/scala/org/apache/spark/sql/ConfigBehaviorSuite.scala, sql/core/src/test/scala/org/apache/spark/sql/execution/datasources/FileIndexSuite.scala
=> syn 3.2.x commit to 3.3.x.qa

sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBaseParser.g4, sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/parser/AstBuilder.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/SparkSqlParser.scala
=> KE-40038 Support Logical View

sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/CoalesceShufflePartitions.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSourceStrategy.scala, sql/core/src/main/scala/org/apache/spark/sql/internal/BaseSessionStateBuilder.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSessionStateBuilder.scala
=> Revert "SP-35241 Reduce the output partition of output stage to avoid produci…"

sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/AdaptiveSparkPlanExec.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/adaptive/CoalesceShufflePartitions.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSourceStrategy.scala, sql/core/src/main/scala/org/apache/spark/sql/internal/BaseSessionStateBuilder.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveSessionStateBuilder.scala
=> Revert "SP-35241 Reduce the output partition of output stage to avoid small files"

pom.xml
AL-7790 set createDependencyReducedPom to false
=> AL-7790 set createDependencyReducedPom to false

bin/docker-image-tool.sh, resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile, resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile.java17
=> adaptive yinglong image

dev/deps/spark-deps-hadoop-2.7-hive-2.3, dev/deps/spark-deps-hadoop-3.2-hive-2.3, docs/sql-data-sources-avro.md, external/avro/src/main/scala/org/apache/spark/sql/avro/AvroOptions.scala, external/avro/src/test/scala/org/apache/spark/sql/avro/AvroSuite.scala, pom.xml, project/SparkBuild.scala
To stay up to date with upstream
Unit tests
Closes #37352 from iemejia/SPARK-39927-avro-1.11.1.
Authored-by: Ismaël Mejía <iemejia@gmail.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
#	dev/deps/spark-deps-hadoop-2.7-hive-2.3
#	dev/deps/spark-deps-hadoop-3-hive-2.3
#	docs/sql-data-sources-avro.md
#	external/avro/src/main/scala/org/apache/spark/sql/avro/AvroOptions.scala #	external/avro/src/test/scala/org/apache/spark/sql/avro/AvroSuite.scala #	pom.xml
#	project/SparkBuild.scala
#	sql/hive/src/test/scala/org/apache/spark/sql/hive/client/HiveClientSuite.scala
=> [SPARK-39927][BUILD] Upgrade to Avro 1.11.1

core/src/main/scala/org/apache/spark/InternalAccumulator.scala, core/src/main/scala/org/apache/spark/deploy/history/FsHistoryProvider.scala, core/src/main/scala/org/apache/spark/executor/InputMetrics.scala, core/src/main/scala/org/apache/spark/executor/TaskMetrics.scala, core/src/main/scala/org/apache/spark/scheduler/DAGScheduler.scala, core/src/main/scala/org/apache/spark/scheduler/SparkListener.scala, core/src/test/scala/org/apache/spark/deploy/history/FsHistoryProviderSuite.scala, core/src/test/scala/org/apache/spark/util/JsonProtocolSuite.scala, dev/deps/spark-deps-hadoop-2.7-hive-2.3, dev/deps/spark-deps-hadoop-3.2-hive-2.3, docs/sql-data-sources-avro.md, external/avro/src/main/scala/org/apache/spark/sql/avro/AvroOptions.scala, external/avro/src/test/scala/org/apache/spark/sql/avro/AvroSuite.scala, pom.xml, project/SparkBuild.scala, sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/FileScanRDD.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala
=> merge spark kylin 4.6.7.0 qa to ga

sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/operation/HiveCommandOperation.java, sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveUtils.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/client/IsolatedClientLoader.scala, sql/hive/src/test/scala/org/apache/spark/sql/hive/IsolatedClientLoaderTest.scala
=> KE-41667 CDP 7.1 support hive client 3.1

sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/operation/HiveCommandOperation.java, sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveUtils.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala
=> KE-41667 [FOLLOW UP] fix error

pom.xml
=> AL-8127 fix snyk, upgrade tomcat-embed-core from 9.0.63 to 9.0.72

pom.xml
=> AL-8127 fix snyk, upgrade tomcat-embed-core from 9.0.68 to 9.0.72

resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/Config.scala, resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/KubernetesClientApplication.scala, resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/submit/LoggingPodStatusWatcher.scala, resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/k8s/KubernetesClusterSchedulerBackend.scala, resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile
=> cherry-pick 3.3 commits

pom.xml, sql/hive-thriftserver/src/main/java/org/apache/hive/service/cli/operation/HiveCommandOperation.java, sql/hive-thriftserver/src/main/scala/org/apache/spark/sql/hive/thriftserver/SparkSQLCLIDriver.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/HiveUtils.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala, sql/hive/src/main/scala/org/apache/spark/sql/hive/client/IsolatedClientLoader.scala, sql/hive/src/test/scala/org/apache/spark/sql/hive/IsolatedClientLoaderTest.scala
=> Ke 4.6.8.0 newten cherrypick

core/src/main/scala/org/apache/spark/SparkContext.scala, core/src/main/scala/org/apache/spark/broadcast/BroadcastManager.scala, sql/core/src/main/scala/org/apache/spark/sql/execution/SQLExecution.scala
=> KE-44348 fix broadcast clean

core/src/main/scala/org/apache/spark/SparkContext.scala
=> KE-44348 fix check style
